# config/schedule.rb
# Generated by whenever
# Use this file to define cron jobs for your application
# Learn more: http://github.com/javan/whenever

# Set timezone to Vietnam (UTC+7)
set :output, "log/cron.log"

# Chạy vào 00:01 Thứ 2 hàng tuần (giờ Việt Nam)
# Tự động tạo đăng ký ca mặc định cho tuần mới
# Lưu ý: Đảm bảo server đã set timezone là Asia/Ho_Chi_Minh
# Nếu server dùng UTC, cần điều chỉnh: 00:01 VN = 17:01 UTC (ngày hôm trước)
every :monday, at: '0:01 am', roles: [:app] do
  rake "shift_registrations:auto_create_default"
end

# Chạy vào 02:00 mỗi sáng (giờ Việt Nam)
# Xử lý các ca làm việc quên checkout
# Nếu có start_time mà chưa có checkout (end_time = null) thì:
# - Set forgot_checkout = true
# - Giữ end_time = null (quên chấm công)
every 1.day, at: '2:00 am', roles: [:app] do
  rake "work_sessions:process_forgot_checkouts"
end

